snapshooters:
  - name: snapshooter
    schedule: "@hourly"
    image: olympeio/dev-tools:1.0.2
    config: |-
        [{
          "name": "snapshooter",
          "rootTags": ["0000000000"],
          "path": "snapshot",
          "server": {
            "user": "admin",
            "password": "******",
            "host": "my-olympe-instance.example.com",
            "port": 443
          },
          "git":{
            "repo": "https://***",
            "branch": "snapshooter",
            "commitMessage": "Snapshoted at {date} in {folder}"
          }
        }]
