apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-frontend" (include "olympe.fullname" .) | trunc 63 | trimSuffix "-" }}
  labels:
    {{- include "olympe.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
    name: {{ printf "%s-frontend" (include "olympe.fullname" .) | trunc 63 | trimSuffix "-" }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      name: http
      protocol: TCP
      targetPort: {{ .Values.frontend.port }}
    - port: 85
      name: http-preview
      protocol: TCP
      targetPort: {{ .Values.frontend.previewPort }}
  selector:
    {{- include "olympe.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
    name: {{ printf "%s-frontend" (include "olympe.fullname" .) | trunc 63 | trimSuffix "-" }}
{{ if .Values.frontend.previewService.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-frontend-preview" (include "olympe.fullname" .) | trunc 63 | trimSuffix "-" }}
  labels:
    {{- include "olympe.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
    name: {{ printf "%s-frontend" (include "olympe.fullname" .) | trunc 63 | trimSuffix "-" }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      name: http
      protocol: TCP
      targetPort: {{ .Values.frontend.port }}
    - port: 85
      name: http-preview
      protocol: TCP
      targetPort: {{ .Values.frontend.previewPort }}
  selector:
    {{- include "olympe.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
    name: {{ printf "%s-frontend" (include "olympe.fullname" .) | trunc 63 | trimSuffix "-" }}
{{- end }}