{{- if .Values.orchestrator.initInstall.enabled -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ printf "%s-%s" (include "olympe.fullname" .) .Values.orchestrator.initInstall.command | trunc 52 | trimSuffix "-" }}
  labels:
    {{- include "olympe.labels" . | nindent 4 }}
    app.kubernetes.io/part-of: toolkit
    app.kubernetes.io/component: {{ .Values.orchestrator.initInstall.command }}
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "2"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: {{ printf "%s-%s" (include "olympe.fullname" .) .Values.orchestrator.initInstall.command | trunc 52 | trimSuffix "-" }}
    spec:
      volumes:
        - name: backup-data
          persistentVolumeClaim:
            claimName: {{ printf "%s-orchestrator-backup-data" (include "olympe.fullname" .) | trunc 63 | trimSuffix "-" }}
      containers:
        - name: {{ .Values.orchestrator.initInstall.command }}
          image: "{{ printf "%s/%s:%s" .Values.toolkit.image.repository .Values.toolkit.image.name .Values.toolkit.image.tag }}"
          args:
            - {{ .Values.orchestrator.initInstall.command }}
          envFrom:
            - configMapRef:
                name: {{ printf "%s-orchestrator-config" (include "olympe.fullname" .) | trunc 63 | trimSuffix "-" }}
            - secretRef:
                name: {{ printf "%s-orchestrator-secret" (include "olympe.fullname" .) | trunc 63 | trimSuffix "-" }}
            - secretRef:
                name: orchestrator-default-secret
                optional: true
          env:
            - name: ORCHESTRATOR_HOST
              value: orchestrator
          resources:
            limits:
              cpu: 200m
              memory: 500Mi
          volumeMounts:
            - name: backup-data
              mountPath: /backupData
      restartPolicy: Never
      serviceAccountName: {{ include "olympe.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.toolkit.podSecurityContext | nindent 8 }}
  backoffLimit: 4
---
{{- end }}