{{- if .Values.networkPolicies.enabled }}

{{ $labels := (include "olympe.labels" .) }}
{{ $labelsSelector := (include "olympe.selectorLabels" .) }}
{{ $rules := concat .Values.networkPolicies.defaultRules .Values.networkPolicies.additionalRules }}
{{- range $k, $v := $rules }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ printf "%s-%s" $.Release.Namespace .name }}
  labels:
    {{- $labels | nindent 4 }}
spec:
  {{- toYaml .spec | nindent 2 }}
{{- end }}


{{- range $k, $v := .Values.serviceApps }}
{{- if (($v.networkPolicy).spec) }}
{{ $policy := $v.networkPolicy.spec }}
{{ $_ := unset $policy "podSelector" }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ printf "%s-%s" $.Release.Namespace $k }}
  labels:
    {{- $labels | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      name: {{ printf "%s-%s" $.Release.Namespace $k }}
  {{- toYaml $policy | nindent 2 }}
{{- end }}
{{- end }}
{{- end }}