{{- if .Values.orchestrator.neo4j.resetDB -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ printf "%s-%s" (include "olympe.fullname" .) (lower .Values.olympeTools.action) | trunc 63 | trimSuffix "-" }}
  labels:
    {{- include "olympe.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ lower .Values.olympeTools.action }}
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: {{ printf "%s-%s" (include "olympe.fullname" .) (lower .Values.olympeTools.action) | trunc 63 | trimSuffix "-" }}
    spec:
      volumes:
        - name: backup-data
          persistentVolumeClaim:
            claimName: {{ printf "%s-orchestrator-backup-data" (include "olympe.fullname" .) | trunc 63 | trimSuffix "-" }}
      containers:
        - name: {{ lower .Values.olympeTools.action }}
          image: "{{ default .Values.appRepository .Values.olympeTools.image.repository }}/{{ .Values.olympeTools.image.name }}:{{ default .Chart.AppVersion .Values.olympeTools.image.tag }}"
          envFrom:
            - configMapRef:
                name: {{ printf "%s-orchestrator-config" (include "olympe.fullname" .) | trunc 63 | trimSuffix "-" }}
            - secretRef:
                name: {{ printf "%s-orchestrator-secret" (include "olympe.fullname" .) | trunc 63 | trimSuffix "-" }}
            - secretRef:
                name: orchestrator-default-secret
                optional: true
          env:
            - name: ACTION
              value: {{ .Values.olympeTools.action }}
            - name: BACKUP_USERS
              value: "false"
            - name: BACKUP_DATA
              value: "false"
            - name: RABBITMQ_PATCHES_DIR
              value: /patches
          resources:
            limits:
              cpu: 200m
              memory: 500Mi
          volumeMounts:
            - name: backup-data
              mountPath: /backupData
            {{- if ne (len .Values.serviceApps) 0}}
            - name: nodes
              mountPath: /nodes
            {{- end }}
      restartPolicy: OnFailure
      securityContext:
        runAsUser: 0
{{- end }}