apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ printf "%s-orchestrator-fs" (include "olympe.fullname" .) | trunc 63 | trimSuffix "-" }}
  labels:
    {{- include "olympe.labels" . | nindent 4 }}
    name: {{ printf "%s-orchestrator-fs" (include "olympe.fullname" .) | trunc 63 | trimSuffix "-" }}
    app.kubernetes.io/component: orchestrator
spec:
  accessModes:
  {{- range .Values.orchestrator.dataVolume.accessModes }}
    - {{ . | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ default "1Gi" .Values.orchestrator.dataVolume.fileService.storage }}
  {{- with .Values.orchestrator.dataVolume.storageClassName }}
  storageClassName: {{ . }}
  {{- end }}
  {{- if (((((.Values).orchestrator).dataVolume).fileService).volumeName) }}
  volumeName: {{ .Values.orchestrator.dataVolume.fileService.volumeName  | trunc 63 | trimSuffix "-" }}
  {{- end }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ printf "%s-orchestrator-backup-data" (include "olympe.fullname" .) | trunc 63 | trimSuffix "-" }}
  labels:
    {{- include "olympe.labels" . | nindent 4 }}
    name: {{ printf "%s-orchestrator-backup-data" (include "olympe.fullname" .) | trunc 63 | trimSuffix "-" }}
    app.kubernetes.io/component: orchestrator
spec:
  accessModes:
  {{- range .Values.orchestrator.dataVolume.accessModes }}
    - {{ . | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ default "1Gi" .Values.orchestrator.dataVolume.backupData.storage }}
  {{- with .Values.orchestrator.dataVolume.storageClassName }}
  storageClassName: {{ . }}
  {{- end }}
  {{- if (((((.Values).orchestrator).dataVolume).backupData).volumeName) }}
  volumeName: {{ .Values.orchestrator.dataVolume.backupData.volumeName | trunc 63 | trimSuffix "-" }}
  {{- end }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ printf "%s-orchestrator-patches" (include "olympe.fullname" .) | trunc 63 | trimSuffix "-" }}
  labels:
    {{- include "olympe.labels" . | nindent 4 }}
    name: {{ printf "%s-orchestrator-patches" (include "olympe.fullname" .) | trunc 63 | trimSuffix "-" }}
spec:
  accessModes:
  {{- range .Values.orchestrator.dataVolume.accessModes }}
    - {{ . | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ default "1Gi" .Values.orchestrator.dataVolume.patches.storage }}
  {{- with .Values.orchestrator.dataVolume.storageClassName }}
  storageClassName: {{ . }}
  {{- end }}
  {{- if (((((.Values).orchestrator).dataVolume).patches).volumeName) }}
  volumeName: {{ .Values.orchestrator.dataVolume.patches.volumeName  | trunc 63 | trimSuffix "-" }}
  {{- end }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ printf "%s-query-service" (include "olympe.fullname" .) | trunc 63 | trimSuffix "-" }}
  labels:
    {{- include "olympe.labels" . | nindent 4 }}
    name: {{ printf "%s-query-service" (include "olympe.fullname" .) | trunc 63 | trimSuffix "-" }}
spec:
  accessModes:
  {{- range .Values.orchestrator.dataVolume.accessModes }}
    - {{ . | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ default "1Gi" .Values.orchestrator.dataVolume.queryService.storage }}
  {{- with .Values.orchestrator.queryService.storageClassName }}
  storageClassName: {{ . }}
  {{- end }}
  {{- if (((((.Values).orchestrator).dataVolume).queryService).volumeName) }}
  volumeName: {{ .Values.orchestrator.dataVolume.queryService.volumeName  | trunc 63 | trimSuffix "-" }}
  {{- end }}