apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-orchestrator-config" (include "olympe.fullname" .) | trunc 63 | trimSuffix "-" }}
  labels:
    {{- include "olympe.labels" . | nindent 4 }}
    app.kubernetes.io/component: orchestrator
data:
  {{- if .Values.orchestrator.haEnabled }}
  CLUSTERING_ENABLED: "true"
  HAZELCAST_SERVICE_NAME: {{ printf "%s-orchestrator-ha" (include "olympe.fullname" .) | trunc 63 | trimSuffix "-" }}
  HAZELCAST_DNS_NAMESPACE: {{ .Release.Namespace }}
  CLUSTERING_REQUIRED_MEMBERS_COUNT: {{ .Values.orchestrator.replicas | quote }}
  {{- else }}
  CLUSTERING_ENABLED: "false"
  {{- end }}
  DB_HOSTNAME: {{ default (printf "%s-neo4j" .Release.Name) .Values.orchestrator.neo4j.hostname }}
  DB_NAME: {{ default "neo4j" .Values.orchestrator.neo4j.dbName }}
  KUBERNETES_NAMESPACE: {{ .Release.Namespace }}
  RABBITMQ_HOST: {{ .Values.orchestrator.rabbitmq.host }}
  RABBITMQ_VIRTUAL_HOST: {{ default "orchestrator" .Values.orchestrator.rabbitmq.vhost }}
  RABBITMQ_ORCHESTRATOR_VHOST: {{ default "orchestrator" .Values.orchestrator.rabbitmq.orchestratorVhost }}
  RABBITMQ_PORT: {{ .Values.orchestrator.rabbitmq.port | quote }}
  RABBITMQ_PROTO: {{ default "amqp" .Values.orchestrator.rabbitmq.proto }}
  DB_URI_SCHEME: {{ .Values.orchestrator.neo4j.protocol }}
  WAIT_FOR_NEO4J: {{ default "120" .Values.orchestrator.waitForNeo4j | quote }}
  RABBITMQ_CLIENT_PREFETCH_SIZE: {{ default "200" .Values.orchestrator.rabbitmq.clientPrefetchSize | quote }}
  JAVA_PROCESS_XMX: {{ default "1g" .Values.orchestrator.javaProcessXmx | quote }}
  ALLOWED_WS_ORIGINS: {{ default "|.*" .Values.orchestrator.allowedWsOrigins | quote }}
  ACTIVITY_TIMEOUT: {{ default "70000000" .Values.orchestrator.activityTimeout | quote }}
  USER_EVENTS_ENABLED: {{ default "false" .Values.orchestrator.userEvents | quote }}
  ORCHESTRATOR_CODE_AS_DATA_DIR: {{ default "/patches" .Values.orchestrator.codeAsDataDir | quote }}