{{- range .Values.orchestrator.components }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-%s" (include "olympe.fullname" $) .name | trunc 63 | trimSuffix "-" }}
  labels:
    {{- include "olympe.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ .name }}
    app.kubernetes.io/part-of: orchestrator
    {{- if $.Values.orchestrator.prometheus.enabled }}
    prometheus.io/scrape: "true"
    prometheus.io/port: "8081"
    {{- end }}
spec:
  selector:
    name: {{ printf "%s-%s" (include "olympe.fullname" $) .name | trunc 63 | trimSuffix "-" }}
    app.kubernetes.io/component: {{ .name }}
    app.kubernetes.io/part-of: orchestrator
  ports:
    - name: {{ .name }}
      port: {{ .port }}
      targetPort: {{ .port }}
    {{- if $.Values.orchestrator.prometheus.enabled }}
    - name: micrometer
      port: 8081
      targetPort: 8081
    {{- end }}
{{- if $.Values.additionalServices.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-%s-preview" (include "olympe.fullname" $) .name | trunc 63 | trimSuffix "-" }}
  labels:
    {{- include "olympe.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ .name }}
    app.kubernetes.io/part-of: orchestrator
spec:
  selector:
    name: {{ printf "%s-%s" (include "olympe.fullname" $) .name | trunc 63 | trimSuffix "-" }}
    app.kubernetes.io/component: {{ .name }}
    app.kubernetes.io/part-of: orchestrator
  ports:
    - name: {{ .name }}
      port: {{ .port }}
      targetPort: {{ .port }}
    {{- if $.Values.orchestrator.prometheus.enabled }}
    - name: micrometer
      port: 8081
      targetPort: 8081
    {{- end }}
{{- end }}
{{- end }}