apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-orchestrator" (include "olympe.fullname" .) | trunc 63 | trimSuffix "-" }}
  labels:
    {{- include "olympe.labels" . | nindent 4 }}
    app.kubernetes.io/component: orchestrator
    {{- if .Values.orchestrator.prometheus.enabled }}
    prometheus.io/scrape: "true"
    prometheus.io/port: "8081"
    {{- end }}
spec:
  selector:
    name: {{ printf "%s-orchestrator" (include "olympe.fullname" .) | trunc 63 | trimSuffix "-" }}
    app.kubernetes.io/component: orchestrator
  ports:
    - name: app
      port: 8080
      targetPort: 8080
    {{- if .Values.orchestrator.prometheus.enabled }}
    - name: micrometer
      port: 8081
      targetPort: 8081
    {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: orchestrator
  labels:
    {{- include "olympe.labels" . | nindent 4 }}
    app.kubernetes.io/component: orchestrator
spec:
  selector:
    name: {{ printf "%s-orchestrator" (include "olympe.fullname" .) | trunc 63 | trimSuffix "-" }}
    app.kubernetes.io/component: orchestrator
  ports:
    - name: app
      port: 8080
      targetPort: 8080
{{- if .Values.orchestrator.haEnabled }}
--- 
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-orchestrator-ha" (include "olympe.fullname" .) | trunc 63 | trimSuffix "-" }}
  labels:
    {{- include "olympe.labels" . | nindent 4 }}
    app.kubernetes.io/component: orchestrator
spec:
  selector:
    name: {{ printf "%s-orchestrator" (include "olympe.fullname" .) | trunc 63 | trimSuffix "-" }}
    app.kubernetes.io/component: orchestrator
  ports:
    - name: hazelcast
      protocol: TCP
      port: 5701
      targetPort: 5701
  clusterIP: None
  type: ClusterIP
{{- end }}
{{ if .Values.orchestrator.previewService.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-orchestrator-preview" (include "olympe.fullname" .) | trunc 63 | trimSuffix "-" }}
  labels:
    {{- include "olympe.labels" . | nindent 4 }}
    app.kubernetes.io/component: orchestrator
    name: {{ printf "%s-orchestrator" (include "olympe.fullname" .) | trunc 63 | trimSuffix "-" }}
spec:
  selector:
    name: {{ printf "%s-orchestrator" (include "olympe.fullname" .) | trunc 63 | trimSuffix "-" }}
    app.kubernetes.io/component: orchestrator
  ports:
    - name: app
      port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: orchestrator-preview
  labels:
    {{- include "olympe.labels" . | nindent 4 }}
    app.kubernetes.io/component: orchestrator
spec:
  selector:
    name: {{ printf "%s-orchestrator" (include "olympe.fullname" .) | trunc 63 | trimSuffix "-" }}
    app.kubernetes.io/component: orchestrator
  ports:
    - name: app
      port: 8080
      targetPort: 8080
{{- end }}