{{- range $k, $v := .Values.serviceApps }}
{{- if ne (.type) "cronJob" }}
{{ $data := dict "root" $ "serviceAppName" $k "serviceApp" $v "defaultImage" $.Values.serviceAppsImage "pullPolicy" $.Values.image.pullPolicy "defaultPort" $.Values.serviceAppsDefaultPort "hosts" $.Values.ingress.hosts }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ printf "%s-%s" (include "olympe.fullname" $) $k | trunc 63 | trimSuffix "-" }}
  {{- if .annotations }}
  annotations:
{{ toYaml .annotations | indent 4 }}
  {{- end }}
  labels:
    {{- include "olympe.labels" $ | nindent 4 }}
    name: {{ printf "%s-%s" (include "olympe.fullname" $) $k | trunc 63 | trimSuffix "-" }}
    app.kubernetes.io/component: backend
spec:
  {{- if eq $.Values.enabled true }}
  replicas: {{ .replicas }}
  {{- else }}
  replicas: 0
  {{- end }}
  selector:
    matchLabels:
      {{- include "olympe.selectorLabels" $ | nindent 6 }}
      name: {{ printf "%s-%s" (include "olympe.fullname" $) $k | trunc 63 | trimSuffix "-" }}
      app.kubernetes.io/component: backend
  template:
    metadata:
    {{- if .podAnnotations }}
      annotations:
{{ toYaml .podAnnotations | indent 8 }}
    {{- end }}
      labels:
        {{- include "olympe.selectorLabels" $ | nindent 8 }}
        name: {{ printf "%s-%s" (include "olympe.fullname" $) $k | trunc 63 | trimSuffix "-" }}
        app.kubernetes.io/component: backend
    spec:
    {{- with $.Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "olympe.serviceAccountName" $ }}
      securityContext:
        runAsUser: 1000
      {{- include "olympe.serviceApps.containers" $data | nindent 6 }}
      {{- include "olympe.serviceApps.volumes" $data | nindent 6 }}
    {{- if $v.nodeSelector }}
    {{- with $v.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- end }}
    {{- with $v.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with $v.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
---
{{- if $v.configMapData }}
{{- if gt (len $v.configMapData) 0 }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-config" $k }}
data:
  {{- range $key, $val := $v.configMapData }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
---
{{- end }}
{{- end }}
{{- if $v.secretData }}
{{- if gt (len $v.secretData) 0 }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-secret" $k }}
type: Opaque
data:
  {{- range $key, $val := $v.secretData }}
  {{ $key }}: {{ $val }}
  {{- end }}
---
{{- end }}
{{- end }}
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-%s" (include "olympe.fullname" $) $k | trunc 63 | trimSuffix "-" }}
spec:
  selector:
    {{- include "olympe.selectorLabels" $ | nindent 4 }}
    name: {{ printf "%s-%s" (include "olympe.fullname" $) $k | trunc 63 | trimSuffix "-" }}
    app.kubernetes.io/component: backend
  ports:
    - name: runtime
      protocol: TCP
      port: 3141
      targetPort: 3141
    {{- if .webservices }}
    - name: webservice
      protocol: TCP
      port: 80
      targetPort: {{ $.Values.serviceAppsDefaultPort }}
    {{- end }}
    {{- if $v.ports }}
    {{- toYaml $v.ports | nindent 4 }}
    {{- end }}
---
{{- end }}
{{- end }}
