{{- if gt (len .Values.serviceApps) 0 }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ printf "%s-nodes-file-service" (include "olympe.fullname" .) | trunc 63 | trimSuffix "-" }}
  labels:
    {{- include "olympe.labels" . | nindent 4 }}
    name: {{ printf "%s-nodes-file-service" (include "olympe.fullname" .) | trunc 63 | trimSuffix "-" }}
spec:
  accessModes:
  {{- range .Values.nodes.dataVolume.accessModes }}
    - {{ . | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ default "1Gi" (((((.Values).nodes).dataVolume).fileService).storage) }}
  {{- with ((((.Values).nodes).dataVolume).storageClassName) }}
  storageClassName: {{ . }}
  {{- end }}
  {{- if (((((.Values).nodes).dataVolume).fileService).volumeName) }}
  volumeName: {{ .Values.nodes.dataVolume.fileService.volumeName | trunc 63 | trimSuffix "-" }}
  {{- end }}
{{- end }}